# Generated by Django 4.2 on 2023-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0002_sample_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='lastname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='middlename',
            new_name='password',
        ),
    ]
