# Generated by Django 4.2 on 2023-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_rename_sample_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(default='unknown', max_length=100, primary_key=True, serialize=False),
        ),
    ]
