# Generated by Django 4.2 on 2023-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0005_remove_registration_id_alter_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='lastname',
            field=models.CharField(default='nolast', max_length=100),
        ),
    ]
